apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-service
  labels:
    app: currency-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-service
  template:
    metadata:
      labels:
        app: currency-service
    spec:
      containers:
        - name: server
          image: ghcr.io/taymazkh/currency-service:latest
          ports:
            - containerPort: 7000
          resources:
            requests:
              cpu: 150m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
