apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  labels:
    app: shipping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
        - name: server
          image: ghcr.io/taymazkh/shipping-service:latest
          ports:
            - containerPort: 50053
          resources:
            requests:
              cpu: 150m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
